### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by jagedn** [nextflow-io/nf-nomad#14]
Use gh-pages to publish an initial version of the documentation to explain the aim, how to use the plugin and so on

**Comment by tomiles** [comment]
Are the [dev docs](https://github.com/nextflow-io/nf-nomad?tab=readme-ov-file#testing-and-debugging) up to date? or do they need some changes to allow testing at this early stage?

**Comment by jagedn** [comment]
yes, I think dev docs is up to date  (I'll review this part `./launch.sh run main.nf -plugins nf-nomad` because I was not using it)

My idea about this issue is to create an "user manual" documentation where explain the configuration, steps to up and running a pipeline, etc

**Comment by abhi18av** [comment]
Dumping some thoughts here regarding updates to dev-docs 

1. Highlight that the minimal Java version needed is `Java-21` for building the project correctly.
2. Document the dev testing setup with (i) `./launch.sh` for local tests and (ii) using Jorge's `nf-plugin-sdk` for testing the published JARs 


Regarding point-2-ii, I'm currently iterating on that 

So here's my plan of action (for a local testing cluster)

- [X] Make a dev release for nf-nomad - `v0.0.1`  => https://github.com/nextflow-io/nf-nomad/releases/tag/0.0.1 
- [ ] Setup a baseline nomad job for triggering nextflow-io/hello pipeline within the dev cluster
- [ ] Prior to running the job, download and setup the `nf-plugin-sdk` 
- [ ] Launch the pipeline on cluster via the nomad-driven NF headjob

**Comment by jagedn** [comment]
@abhi18av , I've created this branch with a minimal, but useless, documentation : https://github.com/nextflow-io/nf-nomad/tree/add-asciidoctor/src/docs/asciidoc

Can you take a look to it and if you think can be useful write down some initial documentation?
