### ISSUE TITLE
Create a new translation class to address NF -> Nomad conversion

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nf-nomad#29]
@jagedn initially suggested a new `TaskResource` class addressing this translation layer.

I do think that we can explore the idea regarding a specific "translation" class which  covers all aspects of `NomadJobDefinition` from a `NextflowTask`, however I suggest that we still continue the current iterations and revisit this once the plugin has stabilised in its design - what do you think?

_Originally posted by @abhi18av in https://github.com/nextflow-io/nf-nomad/pull/27#discussion_r1520634963_

**Comment by jagedn** [comment]
I like your implementation in NomadService using the `TaskRun` , in this way the complexity to build a NomadJob is hidden to NextflowTask so by the moment I think is a good approach

**Comment by jagedn** [comment]
I think this issue is more than covered in current version and we can close it @abhi18av ?

**Comment by abhi18av** [comment]
Agreed Jorge, all the foundations are in he plug-in already 😊
