### ISSUE TITLE
Add possibility to add multiple volumes

### ISSUE THREAD

**Issue by jhaezebr** [nextflow-io/nf-nomad#45]
Other than the working directory, one might need to add more volumes to the job (eg: for reference data).
This would require the following:
- be able to add more than one volume in the workflow config
- be able to define the path where to mount the volume?

**Comment by jhaezebr** [comment]
To me the second option seems cleanest, because there is no redundant 'volume' keyword?

**Comment by jagedn** [comment]
Also you'll be able to "mix" both configurations

```
jobs {
        volume = { type "host" name "scratchdir" }

        volumes = [
            { type "host" name "one" path "/var/data1"},
            { type "host" name "two" path "/var/data2" }
        ]
    }
```

in this case, `scratchdir` will be mounted as `workDir` by default

Or you can specify which volume mount as workdir :

`{ type "host" name "second" workdir true }`
