### ISSUE TITLE
testing on remote environments

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nf-nomad#51]
Hi @jagedn ,

I was wondering if we could have a task which pushes the built plugin to a remote server via SSH.

This was we can use our locally built `latest` version and deploy it to the `sun-nomadlab` or `az-nomadlab` setups - do you think it makes sense?

**Comment by jagedn** [comment]
yes, I think we can use secrets in GH to store the credentials and execute ssh against these server but not sure how to check if the command finish ok ... will see

another approach is to use custom GH runners ( I think we have an issue opened to investigate this case)

**Comment by abhi18av** [comment]
Exactly, with this approach we can push the built aftifacts directly to `az-nomadlab` nodes.

CC @jhaezebr @matthdsm @tomiles
