### ISSUE TITLE
Accommodate NomadSecrets store to resolve Nextflow config-secrets

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nf-nomad#76]
Actually, I must add a clarification here since as of now we have two functional scenarios

| Setup        | LocalStore | NomadStore |
|--------------|------------|------------|
| Config vars  | ✅          | 🔴          |
| Job vars     | ✅          | ✅          |
| sun-nomadlab | ✅          | ✅          |

### ✅ Scenario-1 

Config vars => LocalSecret store

Job vars    => LocalSecret store

### ✅ Scenario-2 

Config vars => LocalSecret store

Job vars    => NomadSecret store

### 🔴  Scenario-3

Config vars => NomadSecret store

Job vars    => NomadSecret store

### Conclusion

@jagedn , please correct me if I'm wrong - in `scenario-3` we can't use the `NomadSecret` store for `config vars` due to the current design decisions on the Nextflow side, however we can support `scenario-1` and `scenario-2` just fine.

_Originally posted by @abhi18av in https://github.com/nextflow-io/nf-nomad/pull/75#discussion_r1694712898_

**Comment by jagedn** [comment]
I think I founded an easy way to have also in config vars 

obviously only case we'll not able to use secrets will be in the own plugin configuration, i.e., 

```
client {
        address = secrets.MY_HOST
    }
```

**Comment by abhi18av** [comment]
Related #81  #79

**Comment by abhi18av** [comment]
@jagedn , the #81 should address scenario-3 described here right? https://github.com/nextflow-io/nf-nomad/issues/76#issue-2434723428

**Comment by jagedn** [comment]
> @jagedn , the #81 should address scenario-3 described here right? [#76 (comment)](https://github.com/nextflow-io/nf-nomad/issues/76#issue-2434723428)

yes, I think with this PR we cover all use cases
