### ISSUE TITLE
Improve job-status query logic and nf-tower support 

### ISSUE THREAD

**Issue by abhi18av** [nextflow-io/nf-nomad#77]
The job query status logic needs to be revamped in order to work well with Tower. 

As of now, the jobs (on Tower) are always shown as running and are not progressing to completed status. Despite being actually completed on the cluster itself.

<img width="668" alt="image" src="https://github.com/user-attachments/assets/e44017d7-edf8-4d8d-8342-644a418513fc">

Also, as a result, the pipeline execution report (within nf-core pipelines) also doesn't contain any relevant information.

<img width="1458" alt="image" src="https://github.com/user-attachments/assets/3a6e21c7-4bf1-42ab-9be3-2e8812b5e5cf">

**Comment by abhi18av** [comment]
@jagedn , now that our `NomadService` class has been refactored, maybe we should pick this up again?

**Comment by jagedn** [comment]
One question:

I've tried to run a simple pipeline using local executor + tower

`nextflow-io/rnaseq-nf --proces.executor=local`

and I can see it is created in tower, but the status of the tasks are not updated and the spinner is always running. If I refresh the page them all looks fine

Is this a typical use case of Tower or I'm doing something wrong and Tower is able to show in runtime, without any refresh, the situation of the tasks ?

`

**Comment by jagedn** [comment]
So, I'm working in a revamp of the status logic and now I can see information in tower running ` ./run-pipeline.sh -c tower/nextflow.config nf-core/fetchngs -profile test -with-tower --outdir $(pwd)/nomad_temp/scratchdir/out`

but Tower doesn't refresh the status of the tasks, I need to refresh the page. Not sure if this is an issue of Tower 

Running this pipeline and once the pipeline completed I can see  :

![imagen](https://github.com/user-attachments/assets/55407703-ae88-4aa7-8f3b-b56df2b7b173)

![imagen](https://github.com/user-attachments/assets/a9f8cf30-2dc5-4c1e-9a9d-7e8f79ea3ba7)

![imagen](https://github.com/user-attachments/assets/e6c993ee-5214-4688-86ef-528084803743)

![imagen](https://github.com/user-attachments/assets/5ad511af-47b1-46af-99c8-438f434c3f74)

![imagen](https://github.com/user-attachments/assets/ece044cf-05ff-49ec-82c2-27039c254a5c)

so from my side it seems is working except tower doesnt refresn in realtime the information (also I was debugging and I was able to see the plugin is sending the info to the remote server during the execution of the pipeline)

**Comment by abhi18av** [comment]
This is great Jorge - and welcome back 😉

I think this can conclude the current iteration and we can make the release for `v0.3.1`. 

Let's create a PR and I can also test locally for this.
